{
 "title": "Mininet Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Premium Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max bitrate over time by switch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(switch_id) (flow_bitrate_mbps)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg packet size by switch [b]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg by(switch_id) (avg_over_time(flow_avg_pkt_size[2d:]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flux durations switch 2 [s]",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "flow_duration_s{switch_id=\"2\"} > 0 < 150",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Flux durations switch 4 [s]",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "flow_duration_s{switch_id=\"4\"} > 0 < 150",
     "legendFormat": " "
    }
   ]
  }
 ]
}